name: Repo Files Sync
on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3.0.0

      - name: Run Repo File Sync Action
        uses: BetaHuhn/repo-file-sync-action@v1
        with:
          ASSIGNEES: |
            ChrisCarini
          # NOTE: As much as I would like to be marked to review each of these, because
          # this GitHub Action uses a PAT, the commit is coming from myself (ie, `ChrisCarini`)
          # and thus, trying to set myself as a reviewer yields the below error message:
          #
          #   "Error: Review cannot be requested from pull request author."
          #
          # REVIEWERS: |
          #   ChrisCarini
          PR_LABELS: |
            repo-file-sync
          CONFIG_PATH: sync.yml
          GH_PAT: ${{ secrets.GH_PAT_REPO_SCOPE }}
